# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20161103_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='home_address',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
