# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20161103_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
